---
# The playbook to deploy a server installation of Chipster
- hosts: chiphosts
  user: ubuntu
  sudo: yes

  vars:
    proxy_env:
      http_proxy: http://192.168.15.254:3128
    chipster_build: "0"
    chipster_version: "3.0.0"
    chipster_url: "http://192.168.15.254/artefacts/chipster/{{ chipster_build }}/chipster-{{ chipster_version }}.tar.gz"
    tools_build: "54"
    tools_url: "http://192.168.15.254/artefacts/build_tools/{{ tools_build }}/"
  roles:
    - common
    - chipster
