---
- name: install dependencies
  apt: pkg={{ item }} state=present  update_cache=yes   cache_valid_time=3600
  with_items:
    - openjdk-7-jdk
    - nfs-common
    - ant
    - git
  register: pkg_install_changed
  environment: proxy_env

- name: set java link
  command: update-java-alternatives -s java-1.7.0-openjdk-amd64
  when: pkg_install_changed

- name: download Chipster
  get_url: url={{ chipster_url }} dest=/tmp/chipster-{{ chipster_build }}.tar.gz
  environment: proxy_env

- name: extract Chipster
  command: creates=/opt/chipster /bin/tar xfz /tmp/chipster-{{ chipster_build }}.tar.gz -C /opt

- name: configure Chipster
  shell: chdir=/opt/chipster ./configure.sh `hostname -I`

- name: generate password for Chipster
  command: chdir=/opt/chipster echo "yes" |./genpassword.sh

- name: symlink /mnt/artefacts/build_tools as /mnt/tools
  file: src=/mnt/artefacts/build_tools/{{ tools_build }} dest=/mnt/tools state=link

- name: symlink /mnt/tools as /opt/chipster/tools
  file: src=/mnt/tools dest=/opt/chipster/tools state=link force=yes

- name: start Chipster
  command: creates=/var/lock/subsys/chipster-comp creates=/var/lock/subsys/chipster-auth creates=/var/lock/subsys/chipster-webstart creates=/var/lock/subsys/chipster-fileserver  chdir=/opt/chipster ./chipster start
