---
- name: install dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - openjdk-7-jdk
    - nfs-common

- name: download Chipster
  get_url: url=http://www.nic.funet.fi/pub/sci/molbio/chipster/dist/versions/2.3.0/chipster-2.3.0.tar.gz dest=/opt mode=0440

- name: extract Chipster
  command: creates=/opt/chipster /bin/tar xfz /opt/chipster-2.3.0.tar.gz -C /opt

- name: configure Chipster
  command: creates=/opt/chipster/comp/conf/chipster-config.xml chdir=/opt/chipster ./configure.sh `hostname -I`

- name: generate password for Chipster
  command: chdir=/opt/chipster echo "yes" |./genpassword.sh

- name: create symlink for Chipster tools
  file: src=/mnt/tools dest=/opt/chipster/tools state=link

- name: start Chipster
  command: creates=/var/lock/subsys/chipster-comp creates=/var/lock/subsys/chipster-auth creates=/var/lock/subsys/chipster-webstart creates=/var/lock/subsys/chipster-fileserver  chdir=/opt/chipster ./chipster start
